#!/usr/bin/env python

import os
import sys
import click
from cfn_sphere.util import convert_file
from cfn_sphere.stack_config import StackConfig
from cfn_sphere.main import StackActionHandler


@click.group(help="This tool manages AWS CloudFormation templates "
                  "and stacks by providing an application scope and useful tooling.")
def cli():
    pass


@cli.command(help="Create an applications infrastructure")
@click.argument('filename', type=click.Path(exists=True))
def sync(filename):
    try:
        working_dir = os.path.dirname(os.path.realpath(filename))

        stack_config = StackConfig(filename)
        StackActionHandler(stack_config, working_dir).create_or_update_stacks()
    except Exception as e:
        click.echo("Error syncinc stacks: {}".format(e))
        sys.exit(1)


@cli.command(help="Convert JSON to YAML or vice versa")
@click.argument('filename', type=click.Path(exists=True))
def convert(filename):
    try:
        click.echo(convert_file(filename))
    except Exception as e:
        click.echo("Error converting file: {}".format(e))
        sys.exit(1)


if __name__ == '__main__':
    cli()